package com.synopsys.integration.rest.it;

public enum TestingPropertyKey {
    TEST_AUTHENTICATED_SERVER_URL,
    TEST_HTTPS_SERVER_URL,
    TEST_AUTO_IMPORT_HTTPS_CERT,
    TEST_TIMEOUT,
    TEST_PROXY_HOST_PASSTHROUGH,
    TEST_PROXY_PORT_PASSTHROUGH,
    TEST_PROXY_HOST_BASIC,
    TEST_PROXY_PORT_BASIC,
    TEST_PROXY_USER_BASIC,
    TEST_PROXY_PASSWORD_BASIC,
    TEST_PROXY_HOST_DIGEST,
    TEST_PROXY_PORT_DIGEST,
    TEST_PROXY_USER_DIGEST,
    TEST_PROXY_PASSWORD_DIGEST,
    TEST_PROXY_HOST_NTLM,
    TEST_PROXY_PORT_NTLM,
    TEST_PROXY_USER_NTLM,
    TEST_PROXY_PASSWORD_NTLM

}
